version = "0.3.2"

# This loads the env file into the environment of bonnie and the executed child process 
# You may need to use the following syntax to interpolate env vars in a bonnie command itself: 
# scriptName.cmd = "command for script with %EXACT_ENV_VAR_NAME for evn var interpolation"
# scriptName.env_vars = ["EXACT_ENV_VAR_NAME"]
# see https://github.com/arctic-hen7/bonnie/wiki/Environment-Variables
env_files = [".env"]

[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    compose = "doppler run -- docker-compose %%"
    # [Internal] - more base commands
    git-pull       = "git pull --ff"
    docker-pull    = "bonnie compose pull"
    docker-cleanup = "docker image prune"

    # everyday scripts
    start.cmd                = "bonnie compose up -d"
    start.subcommands.master = "bonnie compose up -d master"
    start.subcommands.volume = "bonnie compose up -d volume"
    stop                     = "bonnie compose down"
    logs                     = "bonnie compose logs -f -t %%"

    # runs the 'weed' cli on the weed service in docker-compose
    weed = "bonnie compose run weed weed %%"

    # extended scripts
    update = [
        "bonnie stop",
        "bonnie git-pull",
        "bonnie docker-pull",
        "bonnie start-logs",
    ]
    start-logs = ["bonnie start", "bonnie logs"]
    restart = ["bonnie stop", "bonnie start"]
    restart-logs = ["bonnie stop", "bonnie start-logs"]

    # Weed client commands
    # expects the 'weed' executable to be in path and accessible
    mount = "weed mount -filer=localhost:8888 -dir=~/mnt -filer.path=/ -volumeServerAccess=filerProxy"
