version = "0.3.2"

# This loads the env file into the environment of bonnie and the executed child process 
# You may need to use the following syntax to interpolate env vars in a bonnie command itself: 
# scriptName.cmd = "command for script with %EXACT_ENV_VAR_NAME for evn var interpolation"
# scriptName.env_vars = ["EXACT_ENV_VAR_NAME"]
# see https://github.com/arctic-hen7/bonnie/wiki/Environment-Variables
env_files = [".env"]

[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    compose = "doppler run -- docker-compose %%"
    eval    = "doppler secrets get --plain %%"
    up      = "bonnie compose up -d --remove-orphans %%"
    # [Internal] - more base commands
    git-pull       = "git pull --ff"
    docker-pull    = "bonnie compose pull"
    docker-cleanup = "docker image prune"

    # everyday scripts
    start.cmd                    = "bonnie up"
    start.subcommands.master     = "bonnie up master"
    start.subcommands.volume     = "bonnie up volume"
    start.subcommands.filer      = "bonnie up filer"
    start.subcommands.fuse       = "bonnie start fuseproxy"
    start.subcommands.fuseproxy  = "weed -v=4 mount -filer=localhost:8888 -dir=$(bonnie eval LOCAL_FUSE_MOUNTPOINT) -allowOthers -volumeServerAccess=filerProxy -nonempty -replication=000"
    start.subcommands.fusedirect = "weed -v=4 mount -filer=localhost:8888 -dir=$(bonnie eval LOCAL_FUSE_MOUNTPOINT) -allowOthers -volumeServerAccess=direct -nonempty -replication=000"
    start.subcommands.webdav     = "bonnie up webdav"
    stop                         = "bonnie compose down"
    logs                         = "bonnie compose logs -f -t %%"
    weed                         = "bonnie compose run weed %%"
    test-upload                  = "bonnie weed upload -master=\"master:9333\" -dir=\"/examples\""

    # extended scripts
    update = [
        "bonnie stop",
        "bonnie git-pull",
        "bonnie docker-pull",
        "bonnie start-logs",
    ]
    start-logs = ["bonnie start", "bonnie logs"]
    restart = ["bonnie stop", "bonnie start"]
    restart-logs = ["bonnie stop", "bonnie start-logs"]

    # Weed client commands
    # expects the 'weed' executable to be in path and accessible
    # mount = "weed mount -filer=localhost:8888 -dir=$(doppler secrets get --plain LOCAL_FUSE_MOUNTPOINT) -filer.path=/ -volumeServerAccess=filerProxy"
    mount = "weed mount -filer=localhost:8888 -dir=$(bonnie eval LOCAL_FUSE_MOUNTPOINT) -nonempty -volumeServerAccess=filerProxy -replication=000 -filer.path=/ "
