version = "0.3.2"

# This loads the env file into the environment of bonnie and the executed child process 
# You may need to use the following syntax to interpolate env vars in a bonnie command itself: 
# scriptName.cmd = "command for script with %EXACT_ENV_VAR_NAME for evn var interpolation"
# scriptName.env_vars = ["EXACT_ENV_VAR_NAME"]
# see https://github.com/arctic-hen7/bonnie/wiki/Environment-Variables
env_files = [".env"]

[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    compose = "doppler run -- docker-compose %%"

    # Basic Commands
    start = "bonnie compose up -d"
    stop  = "bonnie compose down"

    # Weed client commands
    # expects the 'weed' executable to be in path and accessible
    mount = "weed mount -filer=localhost:8888 -dir=/Volumes/seaweedfs -filer.path=/"
