version: '3'

# Note: all server ip addresses are referenced by docker-compose service name in this file! :) 
# Source compose file: https://raw.githubusercontent.com/chrislusf/seaweedfs/master/docker/seaweedfs-compose.yml

services:
  ### Master Service ###
  master:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 9333:9333
      - 19333:19333
    # -ip=master works, because 'master' is the dns name of this service container
    command: "master -ip=master"

  ### Volume Service ###
  volume:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    volumes: 
      - ${WEED_STORAGE_DIR}:/data
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325  -dir=/data'
    depends_on:
      - master
  
  ### Filer Service ###
  filer:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume

  ### Automatic Fuse Mount of the seaweedfs content to the host system ###
  fusemount: 
    image: ${SEAWEEDFS_IMAGE}
    depends_on:
      - master
      - filer
    # entrypoint: 'nsenter -t 1 -m -u -n -i -- ${WEED_CLI_HOST_PATH} mount -filer="localhost:8888,localhost:8889" -filer.path=/ -dir=${LOCAL_FUSE_MOUNTPOINT}'
    volumes: 
      # Creates a docker bind mount from inside this container to the host machine, 
      # To be able to access the fuse mount binding from the weed executable
      - ${LOCAL_FUSE_MOUNTPOINT}:/mnt/external
    command: 'mount -filer=filer:8888 -dir=/mnt/external -filer.path=/ -volumeServerAccess=direct'

  ### Webdav Interface for this Seaweed instance ###
  webdav:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - ${WEBDAV_PORT}:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer

  weed:
    image: ${SEAWEEDFS_IMAGE}
    restart: "no"
    command: ["echo", "Service weed is only for being used with docker-compose run weed"]
    volumes: 
      - ${EXAMPLES_FOLDER}:/examples
  
  # TODO: Why do I need this cronjob container??
  # cronjob:
  #   image: ${SEAWEEDFS_IMAGE}
  #   command: 'cronjob'
  #   environment:
  #     # Run re-replication every 2 minutes
  #     CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
  #     WEED_MASTER: master:9333 # Default: localhost:9333
  #   depends_on:
  #     - master
  #     - volume