version: '3'

# Note: all server ip addresses are referenced by docker-compose service name in this file! :) 
# Source compose file: https://raw.githubusercontent.com/chrislusf/seaweedfs/master/docker/seaweedfs-compose.yml

services:

  master:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 9333:9333
      - 19333:19333
    # -ip=master works, because 'master' is the dns name of this service container
    command: "master -ip=master"

  volume:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume

  fusemount: 
    image: ${SEAWEEDFS_IMAGE}
    volumes: 
      # Creates a docker bind mount from inside this container to the host machine, 
      # To be able to access the fuse mount binding from the weed executable
      - ${LOCAL_MOUNT_DIR}:/mnt/external
    command: 'mount -filer=filer:8888 -dir=/mnt/external -filer.path=/ -volumeServerAccess=direct'

  webdav:
    image: ${SEAWEEDFS_IMAGE}
    ports:
      - ${WEBDAV_PORT}:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer

  # TODO: Why do I need this cronjob container??
  cronjob:
    image: ${SEAWEEDFS_IMAGE}
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - volume