version = "0.3.2"

# This config allows running seaweedfs on baremetal
[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    doppler = "doppler run -- %%"
    eval    = "doppler secrets get --plain %%"
    weed    = "bonnie doppler weed %%"

    # everyday scripts
    start.cmd                = "bonnie weed server -dir=\"./data\" --filer=true"
    start.subcommands.master = "bonnie weed master -ip=$(bonnie eval WEED_IP_MASTER) -mdir=data"
    start.subcommands.volume = "bonnie weed volume -mserver=\"$(bonnie eval WEED_IP_MASTER):9333\" -port=8080  -metricsPort=9325  -dir=data"
    start.subcommands.filer  = "bonnie weed filer -master=\"$(bonnie eval WEED_IP_MASTER):9333\"  -metricsPort=9326"
    mount                    = "bonnie weed mount -filer=localhost:8888 -dir=$(bonnie eval LOCAL_FUSE_MOUNTPOINT) -filer.path=/ -volumeServerAccess=direct"
