version = "0.3.2"

# This config allows running seaweedfs on baremetal
[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    doppler = "doppler run -- %%"
    eval    = "doppler secrets get --plain %%"
    weed    = "bonnie doppler weed %%"

    # everyday scripts
    start.cmd                = "bonnie weed server -dir=\"./data\" -filer -s3"
    start.subcommands.master = "bonnie weed master -ip=$(bonnie eval WEED_IP_MASTER) -mdir=data"
    start.subcommands.volume = "bonnie weed volume -mserver=\"$(bonnie eval WEED_IP_MASTER):9333\" -port=8080  -metricsPort=9325  -dir=data"
    start.subcommands.filer  = "bonnie weed filer -master=\"$(bonnie eval WEED_IP_MASTER):9333\"  -metricsPort=9326"

    ## Explanations to this mount command
    # -nonempty => since the mountpoint has a .gitkeep file, this is needed to force weed to mount into this folder
    # -replication=000 => files should not be replicated for now (maybe later, when seaweed replaces my zfs install
    # -volumeServerAccess can have options: publicUrl|filerProxy
    mount.cmd              = "echo 'bonnie mount <folder-alias> (example: test)'"
    mountBase              = "bonnie weed -v=4 mount -filer=localhost:8888 -dir=$(bonnie eval LOCAL_FUSE_MOUNTPOINT) -allowOthers -volumeServerAccess=direct -nonempty -replication=000"
    mount.subcommands.root = "bonnie mountBase -filer.path=/ "
    mount.subcommands.test = "bonnie mountBase  -filer.path=/test "
